# Copyright (c) 2020 David Holsgrove
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT (For details, see https://github.com/davidholsgrove/gcp-icons-for-plantuml/blob/master/LICENSE-CODE)
#
# Hand curated config file for GCP Architecture Icon set as of 2020-04-01
#
Defaults:
  Colors:
    GoogleBlue: "#4284F3"
    GoogleRed: "#EA4335"
    GoogleGreen: "#0F9D58"
    GoogleYellow: "#F4B400"
  # Defaults for services not found
  Category:
    Color: GoogleBlue
  # Maximum in either height or width in pixels
  TargetMaxSize: 128
Categories:
- Name: AIAndMachineLearning
  Services:
  - Source: AI Hub.png
    Target: AIHub
  - Source: AI Platform Data Labeling Service.png
    Target: AIPlatformDataLabelingService
  - Source: AI Platform.png
    Target: AIPlatform
  - Source: Advanced Solutions Lab.png
    Target: AdvancedSolutionsLab
  - Source: AutoML Natural Language.png
    Target: AutoMLNaturalLanguage
  - Source: AutoML Tables.png
    Target: AutoMLTables
  - Source: AutoML Translation.png
    Target: AutoMLTranslation
  - Source: AutoML Video Intelligence.png
    Target: AutoMLVideoIntelligence
  - Source: AutoML Vision.png
    Target: AutoMLVision
  - Source: Cloud AutoML.png
    Target: CloudAutoML
  - Source: Cloud Inference API.png
    Target: CloudInferenceAPI
  - Source: Cloud Jobs API.png
    Target: CloudJobsAPI
  - Source: Cloud Natural Language API.png
    Target: CloudNaturalLanguageAPI
  - Source: Cloud Speech-to-Text.png
    Target: CloudSpeechtoText
  - Source: Cloud TPU.png
    Target: CloudTPU
  - Source: Cloud Text-to-Speech.png
    Target: CloudTexttoSpeech
  - Source: Cloud Translation API.png
    Target: CloudTranslationAPI
  - Source: Cloud Video Intelligence API.png
    Target: CloudVideoIntelligenceAPI
  - Source: Cloud Vision API.png
    Target: CloudVisionAPI
  - Source: Dialog Flow Enterprise Edition.png
    Target: DialogFlowEnterpriseEdition
  - Source: Recommendations AI.png
    Target: RecommendationsAI
  SourceDir: AI and Machine Learning
- Name: APIManagement
  Services:
  - Source: API Analytics.png
    Target: APIAnalytics
  - Source: API Monetization.png
    Target: APIMonetization
  - Source: Apigee API Platform.png
    Target: ApigeeAPIPlatform
  - Source: Apigee Sense.png
    Target: ApigeeSense
  - Source: Cloud Endpoints.png
    Target: CloudEndpoints
  - Source: Developer Portal.png
    Target: DeveloperPortal
  SourceDir: API Management
- Name: Compute
  Services:
  - Source: App Engine.png
    Target: AppEngine
  - Source: Cloud Functions.png
    Target: CloudFunctions
  - Source: Cloud Run.png
    Target: CloudRun
  - Source: Compute Engine.png
    Target: ComputeEngine
  - Source: Container-Optimized OS.png
    Target: ContainerOptimizedOS
  - Source: GKE On-Prem.png
    Target: GKEOnPrem
  - Source: GPU.png
    Target: GPU
  - Source: Kubernetes Engine.png
    Target: KubernetesEngine
  SourceDir: Compute
- Name: DataAnalytics
  Services:
  - Source: BigQuery.png
    Target: BigQuery
  - Source: Cloud Composer.png
    Target: CloudComposer
  - Source: Cloud Data Catalog.png
    Target: CloudDataCatalog
  - Source: Cloud Data Fusion.png
    Target: CloudDataFusion
  - Source: Cloud Dataflow.png
    Target: CloudDataflow
  - Source: Cloud Datalab.png
    Target: CloudDatalab
  - Source: Cloud Dataprep.png
    Target: CloudDataprep
  - Source: Cloud Dataproc.png
    Target: CloudDataproc
  - Source: Cloud PubSub.png
    Target: CloudPubSub
  - Source: Genomics.png
    Target: Genomics
  SourceDir: Data Analytics
- Name: Databases
  Services:
  - Source: Cloud Bigtable.png
    Target: CloudBigtable
  - Source: Cloud Datastore.png
    Target: CloudDatastore
  - Source: Cloud Firestore.png
    Target: CloudFirestore
  - Source: Cloud Memorystore.png
    Target: CloudMemorystore
  - Source: Cloud SQL.png
    Target: CloudSQL
  - Source: Cloud Spanner.png
    Target: CloudSpanner
  SourceDir: Databases
- Name: DeveloperTools
  Services:
  - Source: Cloud Build.png
    Target: CloudBuild
  - Source: Cloud Code for IntelliJ.png
    Target: CloudCodeforIntelliJ
  - Source: Cloud Code.png
    Target: CloudCode
  - Source: Cloud SDK.png
    Target: CloudSDK
  - Source: Cloud Scheduler.png
    Target: CloudScheduler
  - Source: Cloud Source Repositories.png
    Target: CloudSourceRepositories
  - Source: Cloud Tasks.png
    Target: CloudTasks
  - Source: Cloud Test Lab.png
    Target: CloudTestLab
  - Source: Cloud Tools for Eclipse.png
    Target: CloudToolsforEclipse
  - Source: Cloud Tools for PowerShell.png
    Target: CloudToolsforPowerShell
  - Source: Cloud Tools for Visual Studio.png
    Target: CloudToolsforVisualStudio
  - Source: Container Registry.png
    Target: ContainerRegistry
  - Source: Gradle App Engine Plugin.png
    Target: GradleAppEnginePlugin
  - Source: IDE Plugins.png
    Target: IDEPlugins
  - Source: Maven App Engine Plugin.png
    Target: MavenAppEnginePlugin
  SourceDir: Developer Tools
- Name: HybridAndMultiCloud
  Services:
  - Source: Stackdriver.png
    Target: HybridStackdriver
  - Source: Traffic Director.png
    Target: HybridTrafficDirector
  SourceDir: Hybrid and Multi Cloud
- Name: InternetOfThings
  Services:
  - Source: Cloud IoT Core.png
    Target: CloudIoTCore
  SourceDir: Internet of Things
- Name: ManagementTools
  Services:
  - Source: Cloud APIs.png
    Target: CloudAPIs
  - Source: Cloud Billing API.png
    Target: CloudBillingAPI
  - Source: Cloud Console.png
    Target: CloudConsole
  - Source: Cloud Deployment Manager.png
    Target: CloudDeploymentManager
  - Source: Cloud Mobile App.png
    Target: CloudMobileApp
  - Source: Cloud Service Mesh.png
    Target: CloudServiceMesh
  - Source: Cloud Shell.png
    Target: CloudShell
  - Source: Debugger.png
    Target: Debugger
  - Source: Error Reporting.png
    Target: ErrorReporting
  - Source: Logging.png
    Target: Logging
  - Source: Monitoring.png
    Target: Monitoring
  - Source: Profiler.png
    Target: Profiler
  - Source: Stackdriver.png
    Target: Stackdriver
  - Source: Trace.png
    Target: Trace
  SourceDir: Management Tools
- Name: Migration
  Services:
  - Source: Transfer Appliance.png
    Target: TransferAppliance
  SourceDir: Migration
- Name: Networking
  Services:
  - Source: Cloud Armor.png
    Target: CloudArmor
  - Source: Cloud CDN.png
    Target: CloudCDN
  - Source: Cloud DNS.png
    Target: CloudDNS
  - Source: Cloud External IP Addresses.png
    Target: CloudExternalIPAddresses
  - Source: Cloud Firewall Rules.png
    Target: CloudFirewallRules
  - Source: Cloud Load Balancing.png
    Target: CloudLoadBalancing
  - Source: Cloud NAT.png
    Target: CloudNAT
  - Source: Cloud Network.png
    Target: CloudNetwork
  - Source: Cloud Router.png
    Target: CloudRouter
  - Source: Cloud Routes.png
    Target: CloudRoutes
  - Source: Cloud VPN.png
    Target: CloudVPN
  - Source: Dedicated Interconnect.png
    Target: DedicatedInterconnect
  - Source: Partner Interconnect.png
    Target: PartnerInterconnect
  - Source: Premium Network Tier.png
    Target: PremiumNetworkTier
  - Source: Standard Network Tier.png
    Target: StandardNetworkTier
  - Source: Traffic Director.png
    Target: TrafficDirector
  - Source: Virtual Private Cloud.png
    Target: VirtualPrivateCloud
  SourceDir: Networking
- Name: Security
  Services:
  - Source: Cloud IAM.png
    Target: CloudIAM
  - Source: Cloud Resource Manager.png
    Target: CloudResourceManager
  - Source: Cloud Security Command Center.png
    Target: CloudSecurityCommandCenter
  - Source: Cloud Security Scanner.png
    Target: CloudSecurityScanner
  - Source: Key Management Service.png
    Target: KeyManagementService
  SourceDir: Security
- Name: Storage
  Services:
  - Source: Cloud Filestore.png
    Target: CloudFilestore
  - Source: Cloud Storage.png
    Target: CloudStorage
  - Source: Persistent Disk.png
    Target: PersistentDisk
  SourceDir: Storage

